backend/cruds/create_db.py, backend/main.py
- mainにAPIに基づいた,APIの枠づくり
- close #19 
- #0
=> feat : add_api

frontend/.storybook/main.js, frontend/.storybook/preview.js, frontend/components/Header/Header.stories.tsx, frontend/components/Header/Header.tsx, frontend/package.json, frontend/yarn.lock
- ヘッダーコンポーネントの作成
- close #7
- #7
=> ヘッダーコンポーネントの作成

frontend/components/Filter/CheckboxItem.tsx, frontend/components/Filter/Filter.stories.tsx, frontend/components/Filter/Filter.tsx, frontend/components/Spacer/Spacer.tsx, frontend/store/dummyData.ts
- フィルター周りのコンポーネントの作成
- close #8
- #8
=> フィルター周りのコンポーネントの作成

frontend/components/inputForm/InputForm.stories.tsx, frontend/components/inputForm/InputForm.tsx, frontend/components/inputForm/SelectForm.tsx, frontend/store/dummyData.ts
- 入力フォーム周りのコンポーネントの作成
- close #10
- close #11
- close #12
- close #13
- close #14
- #10 
- #11 
- #12 
- #13 
- #14
=> 入力フォーム周りのコンポーネントの作成

frontend/components/internInfo/CustomText.tsx, frontend/components/internInfo/InternInfo.stories.tsx, frontend/components/internInfo/InternInfo.tsx, frontend/store/dummyData.ts
- インターン情報の詳細コンポーネントの作成
- close #29
- #29
=> インターン情報の詳細コンポーネントの作成

frontend/components/Filter/Filter.tsx, frontend/store/dummyData.ts
API 設計を変更したため
- xxx
- close #33
- #33
=> ダミーデータの形を修正

frontend/components/Filter/CheckboxItem.tsx, frontend/components/Filter/CustomAccordionItem.tsx, frontend/components/Filter/Filter.tsx, frontend/store/dummyData.ts
- フィルター周りのロジックの追加
- close #26
- #26
=> フィルター周りのロジックの追加

frontend/components/Header/Header.tsx, frontend/hooks/useAuth.tsx, frontend/store/Recoil.tsx
- ユーザーアイコンを取得してきたものに変更
- close #43
- #43
=> ユーザーアイコンを取得してきたものに変更

frontend/components/Header/Header.tsx
- ホームから投稿画面への遷移
- close #47
- #47
=> ホームから投稿画面への遷移

frontend/components/Table/CustomTable.tsx
- テーブルから詳細情報への遷移
- close #45
- #45
=> テーブルから詳細情報への遷移

frontend/components/Header/Header.tsx, frontend/hooks/useAuth.tsx, frontend/store/Recoil.tsx
- ホーム→投稿情報ページへの導線の追加
- close #48
- #48
=> ホーム→投稿情報ページへの導線の追加

frontend/components/Table/UserTable.tsx, frontend/pages/user/[id]/index.tsx
- 投稿情報の削除に関するロジックの追加
- close #59
- #59
=> 投稿情報の削除に関するロジックの追加

frontend/components/InputForm/InputForm.tsx, frontend/components/Table/UserTable.tsx, frontend/pages/edit/[uid]/[internId]/index.tsx, frontend/pages/post.tsx
- 編集周りのロジックの追加
- close #60
- #60
=> 編集周りのロジックの追加

frontend/components/Table/CustomTable.tsx
- 一覧で表示されるインターン情報を API から取得してきたものに変更 (フィルター未実装)
- #68
=> 一覧で表示されるインターン情報を API から取得してきたものに変更 (フィルター未実装)

frontend/components/Filter/Filter.tsx, frontend/components/Table/CustomTable.tsx, frontend/pages/index.tsx
- フィルターの変更による表示されるデータの変更
- close #68
- #68
=> フィルターの変更による表示されるデータの変更

backend/main.py
=> feat : cors

frontend/components/Table/UserTable.tsx, frontend/pages/user/[id]/index.tsx, frontend/store/dummyData.ts
- GET/intern-info-list-uid を用いたデータの置き換え
- close #70
- #70
=> GET/intern-info-list-uid を用いたデータの置き換え

frontend/components/InputForm/InputForm.stories.tsx, frontend/components/InputForm/InputForm.tsx
- 入力部分ですべての項目を必須に変更
- close #98
- #98
=> 入力部分ですべての項目を必須に変更

frontend/components/InputForm/InputForm.tsx, frontend/pages/post.tsx
- 入力周りの style の修正
- close #106
- #106
=> 入力周りの style の修正

frontend/components/InputForm/InputForm.tsx
- 投稿完了時に toast の表示
- close #109
- #109
=> 投稿完了時に toast の表示

frontend/pages/_app.tsx, frontend/pages/edit/[uid]/[internId]/index.tsx, frontend/pages/index.tsx, frontend/pages/intern-info/[id]/index.tsx, frontend/pages/post.tsx, frontend/pages/user/[id]/index.tsx
- header の render を減らす
- close #114
- #114
=> header の render を減らす

frontend/components/Table/CustomTable.tsx, frontend/pages/index.tsx
- ページネーションの追加
- close #116
- #116
=> ページネーションの追加

frontend/components/InternInfo/InternInfo.tsx
=> インターン情報フォント修正

backend/cruds/create_db.py, backend/cruds/select_get_filed.py
=> fix : search_

frontend/components/Filter/Filter.tsx
=> refactor: フィルターのマジックナンバーの修正

frontend/components/InputForm/InputForm.tsx, frontend/components/InternInfo/InternInfo.tsx, frontend/components/Table/CustomTable.tsx, frontend/pages/index.tsx
- 入力フォームetc… のスタイルの修正
- close #119
- #119
=> 入力フォームetc… のスタイルの修正

frontend/components/InternInfo/InternInfo.stories.tsx, frontend/components/InternInfo/InternInfo.tsx, frontend/pages/intern-info/[id]/index.tsx
- インターン詳細情報周りのリファクタリング
- close #129
- #129
=> インターン詳細情報周りのリファクタリング

frontend/components/Filter/Filter.stories.tsx, frontend/components/Table/CustomTable.stories.tsx, frontend/components/Table/CustomTable.tsx, frontend/components/Table/UserTable.tsx
- テーブルコンポーネント周りのリファクタリング
- close #130
- #130
=> テーブルコンポーネント周りのリファクタリング

frontend/components/Filter/CheckboxItem.tsx, frontend/components/Table/CustomTable.tsx, frontend/pages/index.tsx
- コンソールの警告の削除
- Storybook に出ている警告はぱっと解消しそうになかったため一旦黙認している
- close #131
- #131
=> コンソールの警告の削除
